apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: leader-election-challenge-hpa
  namespace: leader-election
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: leader-election-challenge
  minReplicas: 3
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
