apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: leader-election-challenge-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: leader-election-challenge
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 1
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 1
